#3. In the above access_switch.j2 template use a Jinja2 for loop to
#create all of the interfaces from FastEthernet 0/1 to FastEthernet 0/24.
#Each of the interfaces should have the following configuration:
#
#>>>>
#interface FastEthernet 0/X                    # where X is the interface number
# switchport access vlan {{item.access_vlan}}                
# switchport mode access
# spanning-tree portfast  
#>>>>
#
#For reference on the for loop syntax see the Jinja2 documentation or
#look at my solution on GitHub at:
#https://github.com/ktbyers/pynet/tree/master/pyth_ans_ecourse/class5/exercise3/roles/access_switch/templates
---
- name: Generate a new Switch configuration file
  # Directory path not needed, Ansible looks for it under tasks dir.
  template: src=access_switch_ex3.j2 
            dest=/home/pluu/PYTHON_4_NTWK_ENGRS/wk5_hw/ex3_ansible/CFG/{{item.hostname}}.txt
  with_items: homework_switches

