---
- name: Generate a new Switch configuration file
  template: src=access_switch_ex3.j2
            dest=/home/pluu/PYTHON_4_NTWK_ENGRS/wk5_hw/ex4_ansible/CFG/{{item.hostname}}.txt
  with_items: test_switches

