#2. Expand upon the above template by adding a Jinja2 if conditional.  The if conditional should add
#the below SNMPv3 commands and associated ACL (i.e. if SNMPv3, then the below commands are added
#into the configuration file):
#>>>>
#access-list 98 remark *** SNMP ***
#access-list 98 permit any
#!
#snmp-server view VIEWSTD iso included
#snmp-server group READONLY v3 priv read VIEWSTD access 98
#snmp-server user pysnmp READONLY v3 auth sha auth_key priv aes 128 encrypt_key
#>>>>
---
- hosts: localhost
  # vars:
    # hostname: pynet-rtr1
  tasks:             # Can have multiple tasks like 3 tasks below
  - name: Generate a new Switch configuration file
    template: src=/home/pluu/PYTHON_4_NTWK_ENGRS/wk5_hw/ex2_ansible/access_switch.j2
              dest=/home/pluu/PYTHON_4_NTWK_ENGRS/wk5_hw/ex2_ansible/{{item.hostname}}.txt
    with_items:
        - { hostname: pynet-sw1, 
            secret: cisco, 
            access_vlan: 100,
            ip_addr: 192.168.100.2,
            default_gateway: 192.168.100.1,
            SNMPv3: True,
            snmp_community: public
          } 
        - { hostname: pynet-sw2, 
            secret: cisco, 
            access_vlan: 200,
            ip_addr: 192.168.200.2,
            default_gateway: 192.168.200.1,
            SNMPv3: True,
            snmp_community: public
          } 
        - { hostname: pynet-sw3, 
            secret: cisco, 
            access_vlan: 300,
            ip_addr: 192.168.300.2,
            default_gateway: 192.168.300.1,
            SNMPv3: False,
            snmp_community: public
          } 
        - { hostname: pynet-sw4, 
            secret: cisco, 
            access_vlan: 400,
            ip_addr: 192.168.400.2,
            default_gateway: 192.168.400.1,
            SNMPv3: True,
            snmp_community: public
          } 
        - { hostname: pynet-jnpr-srx1, 
            secret: cisco, 
            access_vlan: 500,
            ip_addr: 192.168.500.2,
            default_gateway: 192.168.500.1,
            SNMPv3: False,
            snmp_community: public
          } 
